name: (make

on:
  workflow_dispatch:
    

permissions:
  contents: write

jobs:
  crowdin:
    runs-on: ubuntu-latest
    environment: devkitpro/devkitppc:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cmake converter
        run: |
          echo sudo\ apt\ install\ \"\*multi\"\ \"multi\*\" 
          
          pip install cmake_converter
          cmake-converter -s TeconMoon\'s\ WiiVC\ Injector.sln
          cmake . 
          
          make -j66
          ls -a
         
      - name: Upload
  # You may pin to the exact commit or the version.
  # uses: Shopify/upload-to-release@c77c9b3e5d288adaef98a7007bf92340ec6ce03b
        uses: Shopify/upload-to-release@v2.0.0
        with: 
          name: poo
          path: .
